<?php 
$input = <<<INPUT
body {
    background-image:url('http://abc.com/foo.jpg?</style><script>alert(1);</script>');
}
INPUT;

$escaper    = new \Zend\Escaper\Escaper('utf-8');
$output     = $escaper->escapeCss($input); 
?>
<!DOCTYPE html>
<?php //header('Content-Type: application/xhtml+xml; charset=UTF-8'); ?>
<html xhmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta charset="UTF-8"/>
        <title>Unescaped Entities</title>
        <style><?php echo $output; ?></style>
    </head>
    <body>
        <p>
            json_encode() is not good for escaping javascript!
        </p>
    </body>
</html>