<?php 
$input = <<<INPUT
        bar&quot;; alert(&quot;Meow!&quot;); var xss=&quot;true
INPUT;

$output = json_encode($input);
// $output = htmlentities($input);
// $output = htmlspecialchars($input);
?>
<!DOCTYPE html>
<?php //header('Content-Type: application/xhtml+xml; charset=UTF-8'); ?>
<html xhmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta charset="UTF-8"/>
        <title>Unescaped Entities</title>
        <script type="text/javascript">
        var foo = <?php echo $output; ?>
            
        </script>
    </head>
    <body>
        <p>
            json_encode() is not good for escaping javascript!
        </p>
    </body>
</html>